version: '3.3'

services:

  db:
    build: db
    image: MaksimUsov/test-db

  words:
    build: words
    image: MaksimUsov/test-api
    deploy:
      replicas: 5

  web:
    build: web
    image: MaksimUsov/test-web
    ports:
     - "8080:80"
