version: '3.3'

services:

  db:
    image: MaksimUsov/test-db

  words:
    image: MaksimUsov/test-api
    deploy:
      replicas: 5

  web:
    image: MaksimUsov/test-web
    ports:
     - "8080:80"
